/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hitungcal;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows10
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
//    instance object
    HitungCal Nasi = new HitungCal("Nasi",204,1);
    HitungCal Mie = new HitungCal("Mie",305,1);
    HitungCal Roti = new HitungCal("Roti",200,1);
    HitungCal Sarden = new HitungCal("Sarden",25,1);
    HitungCal Tempe = new HitungCal("Tempe",193,1);
    HitungCal Kornet = new HitungCal("Kornet",70,1);
//    memasukan object kedalam array agar mudah
    HitungCal[] makanan = {Nasi,Mie,Roti,Sarden,Tempe,Kornet};
//    ////////////////////////////
        Random random = new Random();
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNama = new javax.swing.JLabel();
        lblNamaUser = new javax.swing.JTextField();
        lblCalorie = new javax.swing.JLabel();
        lblLimitCalorie = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalCalorie = new javax.swing.JTextField();
        fldKeputusan = new javax.swing.JTextField();
        lblKeputusan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTable jTable1 = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        fldJumlahMakanan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblNama.setText("Nama");

        lblCalorie.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lblCalorie.setText("Calorie");

        btnHitung.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnHitung.setText("Hitung !");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setText("Total calorie makanan");

        fldKeputusan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        fldKeputusan.setText("Silahkan masukan data anda !!");

        lblKeputusan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblKeputusan.setText("Keputusan");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, "Nasi", "1 Piring", 204},
                {2, "Mie", "80 gr", 305},
                {3, "Roti", "74 gr", 200},
                {4, "Sarden", "1 kaleng", 25},
                {5,"Tempe","100 gr",193},
                {6,"Kornet","50 gr",70}
            },
            new String [] {
                "No", "Nama", "Jumlah", "Calorie"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnExit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel2.setText("Jumlah/hari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTotalCalorie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCalorie, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fldJumlahMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLimitCalorie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblKeputusan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fldKeputusan, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fldKeputusan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCalorie, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLimitCalorie, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(lblTotalCalorie, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKeputusan)
                            .addComponent(fldJumlahMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
//        mendapatkan identitas user
        String nama = lblNamaUser.getText();
//  mendapatkan pilihan user
        int kaloriUser = Integer.parseInt(lblLimitCalorie.getText());
      int jumlahMakananPerHari = Integer.parseInt(fldJumlahMakanan.getText());
        


       
//            inisialisasi array yg menampung daftar makanan
        ArrayList<HitungCal> makananLolosSeleksi = new ArrayList<HitungCal>();
        
        //memberikan limit kalori permakanan
        int rateKaloriUserPerMakanan = kaloriUser / jumlahMakananPerHari;
      
        
        int totalCalorieMakanan = 0;
     
       
        //memasukan makanan kedalam array
        for(int i = 0;i < makanan.length ;i++){
                if(makanan[i].getCalorieMakanan() <= rateKaloriUserPerMakanan){
                    makananLolosSeleksi.add(makanan[i]);
                }
        }
        
        //  for debugging !!
//               for(int i = 0;i< makananLolosSeleksi.size();i++){
//                   System.out.println(makananLolosSeleksi.get(i).getMakanan());
//               }        
        
//---------------------- masih terdapat bug dibagian ini ----------------------------------------

        //random makanan yang akan ditampilkan
        ArrayList<String> tampilkanMakanan = new ArrayList<String>();
     
        for(int j = 0; j < jumlahMakananPerHari ; j++){
            int rand_int2 = random.nextInt(makananLolosSeleksi.size());
            //jika index masih 0 
            if(tampilkanMakanan.size() == 0){
                   tampilkanMakanan.add(makananLolosSeleksi.get(rand_int2).getMakanan()); 
                   totalCalorieMakanan += makananLolosSeleksi.get(rand_int2).getCalorieMakanan();
                    //for debuging
                   // System.out.println(makananLolosSeleksi.get(rand_int2).getMakanan());
            }
            else{
                //melooping array yang akan ditampilkan untuk dicek isinya
                  for(int z = 0; z < tampilkanMakanan.size();z++){
                      //jika makanan yang diradom sudah ada pada isi array
                      if( tampilkanMakanan.get(z).equals(makananLolosSeleksi.get(rand_int2))){
                          j--;
                          break;
                      }
                      //jika keseluruhan isi array sudah dicek dan tidak mendapati isi yang sama
                      else if( z == tampilkanMakanan.size() - 1){
                           tampilkanMakanan.add(makananLolosSeleksi.get(rand_int2).getMakanan()); 
                           totalCalorieMakanan += makananLolosSeleksi.get(rand_int2).getCalorieMakanan();
                           //for debuging
                         //  System.out.println(makananLolosSeleksi.get(rand_int2).getMakanan());
                           break;
                      }
                  }
             }
       }     
//  array tidak bisa di isi dengan radom yang acak,masih terdapat isi yang sama      
// ------------------------------- masih terdapat bug ----------------------------------------------
        

        String message = "";
        
        int no = 1;
        for(int k = 0;k < tampilkanMakanan.size();k++){
           message += no + ")" + tampilkanMakanan.get(k) + " " ;
           //for debugging !!
            //System.out.println(tampilkanMakanan.get(k));
            no++;
        }

        

       
      
// menampilkan output
//menampilkan output untuk total calorie
        lblTotalCalorie.setText(Integer.toString(totalCalorieMakanan));

        //for debuging !!
        fldKeputusan.setText("Saran makanan : " + message);
        
        
    }//GEN-LAST:event_btnHitungActionPerformed
    
    
    private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("exit");
        if(JOptionPane.showConfirmDialog(frame,"Yakin akan keluar??","Hitung Calorie",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        fldKeputusan.setText("");
        lblNamaUser.setText("");
        lblLimitCalorie.setText("");
        lblTotalCalorie.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField fldJumlahMakanan;
    private javax.swing.JTextField fldKeputusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCalorie;
    private javax.swing.JLabel lblKeputusan;
    private javax.swing.JTextField lblLimitCalorie;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTextField lblNamaUser;
    private javax.swing.JTextField lblTotalCalorie;
    // End of variables declaration//GEN-END:variables
}
